server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shop?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      username: gwon
      password: gwon

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false
        format_sql: true
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
    redis:
      namespace: session
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher